#!/usr/bin/tcsh
# ===========================================================================
# 
# svncopy --
# make new svn copies in the PROG path (only needed by maintainer)
# 
# This file is part of the following software:
# 
#    - the low-level C++ template SIMD library
#    - the SIMD implementation of the MinWarping and the 2D-Warping methods 
#      for local visual homing.
# 
# The software is provided based on the accompanying license agreement
# in the file LICENSE or LICENSE.doc. The software is provided "as is"
# without any warranty by the licensor and without any liability of the
# licensor, and the software may not be distributed by the licensee; see
# the license agreement for details.
# 
# (C) Ralf Möller
#     Computer Engineering
#     Faculty of Technology
#     Bielefeld University
#     www.ti.uni-bielefeld.de
# 
# ===========================================================================

if ($# != 2) then
   echo "svncopy OLDVERSION NEWVERSION"
   exit
endif

set oldVersion = $1
set newVersion = $2

set svnDirList = ( \
	    libraries/SIMDImage \
	    applications/SIMDImageTest \
	    libraries/TiltSearch \
	    applications/TiltSearchTest \
	    libraries/TSIMD \
	    applications/TSIMDTest \
	)
	
foreach svnDir ($svnDirList)
    echo processing $svnDir
    set oldDir = ${VCTL_ARCHIVE}/${svnDir}-${oldVersion}
    set newDir = ${VCTL_ARCHIVE}/${svnDir}-${newVersion}
    if (! -e $oldDir) then
	echo "ERROR: $oldDir is missing"
	exit
    endif
    if (-e $newDir) then
	echo "ERROR: $newDir already exists"
	exit
    endif
    svn copy $oldDir $newDir
end
