#!/usr/bin/tcsh
# ===========================================================================
# 
# update_dir --
# update .dir files to new version (only needed by maintainer)
# 
# This file is part of the following software:
# 
#    - the low-level C++ template SIMD library
#    - the SIMD implementation of the MinWarping and the 2D-Warping methods 
#      for local visual homing.
# 
# The software is provided based on the accompanying license agreement
# in the file LICENSE or LICENSE.doc. The software is provided "as is"
# without any warranty by the licensor and without any liability of the
# licensor, and the software may not be distributed by the licensee; see
# the license agreement for details.
# 
# (C) Ralf Möller
#     Computer Engineering
#     Faculty of Technology
#     Bielefeld University
#     www.ti.uni-bielefeld.de
# 
# ===========================================================================

if ($# != 2) then
   echo "update_dir OLDVERSION NEWVERSION"
   exit
endif

set oldVersion = $1
set newVersion = $2

foreach dirFile (`ls -1 *.dir`)
   echo processing $dirFile
   sed -i "s/${oldVersion}/${newVersion}/g" $dirFile
end
